<a href="https://colab.research.google.com/github/SauravNigam01/CreditCardFraud_ML/blob/main/CreditCardFraud.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [88]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [89]:
df  = pd.read_csv('creditcard.csv')

In [90]:
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [91]:
df.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

In [92]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [93]:
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [94]:
df['Class'].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

In [95]:
#Data is highly unbalance
#Seperating the data for analysis

In [96]:
Legit = df[df.Class==0]
Fraud = df[df.Class==1]

In [97]:
print(Legit.shape)
print(Fraud.shape)

(284315, 31)
(492, 31)

In [98]:
Legit.Amount.describe()

count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64

In [99]:
Fraud.Amount.describe()

count     492.000000
mean      122.211321
std       256.683288
min         0.000000
25%         1.000000
50%         9.250000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

In [100]:
df.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,94838.202258,0.008258,-0.006271,0.012171,-0.007860,0.005453,0.002419,0.009637,-0.000987,0.004467,...,-0.000644,-0.001235,-0.000024,0.000070,0.000182,-0.000072,-0.000089,-0.000295,-0.000131,88.291022
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

In [101]:
#Undersampling

In [102]:
Legit_sample = Legit.sample(n=423)

In [103]:
new_df = pd.concat([Legit_sample,Fraud],axis = 0)

In [104]:
new_df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
241431,151020.0,-0.278250,0.525445,0.453875,-0.965515,0.610422,-0.005460,0.956994,0.030494,-0.035225,...,0.262221,0.888424,-0.182932,0.767690,-0.149048,0.067106,0.133019,0.169068,44.22,0
224383,143766.0,2.061998,-0.057422,-1.259604,0.367123,-0.091320,-1.261283,0.161144,-0.337776,0.702693,...,0.259888,0.906728,0.012485,0.012723,0.223757,-0.097175,-0.015840,-0.059112,1.00,0
103833,68815.0,-1.457546,0.639244,1.530027,0.238469,0.900968,-0.103292,0.553336,0.132431,-0.330182,...,-0.019520,0.229926,-0.359173,0.047124,0.311686,-0.487978,0.142293,0.190394,25.87,0
268998,163481.0,2.088409,-0.965893,-1.253769,-0.692841,-0.809410,-1.293036,-0.283549,-0.332615,-0.190944,...,-0.005947,-0.132635,0.188215,0.026524,-0.131435,-0.333411,-0.049489,-0.051938,73.00,0
236725,148927.0,1.930399,-0.347009,-0.202636,0.361464,-0.684694,-0.399257,-0.576097,0.083471,1.030020,...,-0.119574,-0.220632,0.380734,-0.029973,-0.487951,-0.641208,0.034343,-0.041139,5.00,0

In [105]:
new_df.describe()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
count,915.000000,915.000000,915.000000,915.000000,915.000000,915.000000,915.000000,915.000000,915.000000,915.000000,...,915.000000,915.000000,915.000000,915.000000,915.000000,915.000000,915.000000,915.000000,915.000000,915.000000
mean,88555.949727,-2.549712,1.945513,-3.792172,2.448921,-1.693269,-0.744289,-3.000938,0.338949,-1.390887,...,0.389182,0.014578,-0.015415,-0.048276,0.010255,0.021697,0.089372,0.037438,107.786044,0.537705
std,48750.530440,5.660705,3.775970,6.348767,3.232509,4.325788,1.786028,6.008969,5.034513,2.363667,...,2.889214,1.191646,1.196557,0.556853,0.686054,0.476589,1.041499,0.432460,223.941537,0.498849
min,406.000000,-30.552380,-9.961478,-31.103685,-3.490212,-22.105532,-6.406267,-43.557242,-41.044261,-13.434066,...,-22.797604,-8.887017,-19.254328,-2.790479,-4.781606,-1.172494,-7.263482,-2.556631,0.000000,0.000000
25%,44765.500000,-2.994962,-0.173332,-5.404379,0.030091,-1.924708,-1.677360,-3.457090,-0.174632,-2.461589,...,-0.142388,-0.521981,-0.247237,-0.402801,-0.320193,-0.301874,-0.061867,-0.063852,1.100000,0.000000
50%,84204.000000,-0.937843,1.074932,-1.572939,1.493958,-0.510732,-0.641393,-0.744700,0.161883,-0.794944,...,0.164539,0.041657,-0.042685,-0.002651,0.050678,-0.033355,0.054271,0.035883,18.860000,1.000000
75%,136861.500000,1.011532,2.996150,0.176702,4.455576,0.518829,-0.022912,0.222506,0.949598,0.115231,...,0.700516,0.595329,0.202703,0.375462,0.394439,0.342058,0.483387,0.233469,99.990000,1.000000
max,172397.000000,2.327152,22.057729,3.862590,12.114672,11.095089,6.474115,5.802537,20.007208,6.171399,...,27.202839,8.361985,5.466230,1.236092,2.208209,2.813120,3.052358,1.779364,2125.870000,1.000000

In [106]:
new_df['Class'].value_counts()

Class
1    492
0    423
Name: count, dtype: int64

In [107]:
new_df.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,97638.924350,0.035017,-0.006513,-0.022371,0.014384,0.002509,0.015750,-0.014285,0.069470,-0.006499,...,0.013102,0.011857,0.015194,0.013539,0.017853,-0.026028,-0.013139,-0.005078,-0.007027,91.007707
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

In [108]:
X = new_df.drop(columns='Class' , axis =1)
Y = new_df['Class']

In [109]:
print(X)

            Time        V1        V2        V3        V4        V5        V6  \
241431  151020.0 -0.278250  0.525445  0.453875 -0.965515  0.610422 -0.005460
224383  143766.0  2.061998 -0.057422 -1.259604  0.367123 -0.091320 -1.261283
103833   68815.0 -1.457546  0.639244  1.530027  0.238469  0.900968 -0.103292
268998  163481.0  2.088409 -0.965893 -1.253769 -0.692841 -0.809410 -1.293036
236725  148927.0  1.930399 -0.347009 -0.202636  0.361464 -0.684694 -0.399257
...          ...       ...       ...       ...       ...       ...       ...
279863  169142.0 -1.927883  1.125653 -4.518331  1.749293 -1.566487 -2.010494
280143  169347.0  1.378559  1.289381 -5.004247  1.411850  0.442581 -1.326536
280149  169351.0 -0.676143  1.126366 -2.213700  0.468308 -1.120541 -0.003346
281144  169966.0 -3.113832  0.585864 -5.399730  1.817092 -0.840618 -2.943548
281674  170348.0  1.991976  0.158476 -2.583441  0.408670  1.151147 -0.096695

              V7        V8        V9  ...       V20       V21       V22  \
241431  0.956994  0.030494 -0.035225  ... -0.045787  0.262221  0.888424
224383  0.161144 -0.337776  0.702693  ... -0.280420  0.259888  0.906728
103833  0.553336  0.132431 -0.330182  ... -0.176020 -0.019520  0.229926
268998 -0.283549 -0.332615 -0.190944  ...  0.001573 -0.005947 -0.132635
236725 -0.576097  0.083471  1.030020  ... -0.237466 -0.119574 -0.220632
...          ...       ...       ...  ...       ...       ...       ...
279863 -0.882850  0.697211 -2.064945  ...  1.252967  0.778584 -0.319189
280143 -1.413170  0.248525 -1.127396  ...  0.226138  0.370612  0.028234
280149 -2.234739  1.210158 -0.652250  ...  0.247968  0.751826  0.834108
281144 -2.208002  1.058733 -1.632333  ...  0.306271  0.583276 -0.269209
281674  0.223050 -0.068384  0.577829  ... -0.017652 -0.164350 -0.295135

             V23       V24       V25       V26       V27       V28  Amount
241431 -0.182932  0.767690 -0.149048  0.067106  0.133019  0.169068   44.22
224383  0.012485  0.012723  0.223757 -0.097175 -0.015840 -0.059112    1.00
103833 -0.359173  0.047124  0.311686 -0.487978  0.142293  0.190394   25.87
268998  0.188215  0.026524 -0.131435 -0.333411 -0.049489 -0.051938   73.00
236725  0.380734 -0.029973 -0.487951 -0.641208  0.034343 -0.041139    5.00
...          ...       ...       ...       ...       ...       ...     ...
279863  0.639419 -0.294885  0.537503  0.788395  0.292680  0.147968  390.00
280143 -0.145640 -0.081049  0.521875  0.739467  0.389152  0.186637    0.76
280149  0.190944  0.032070 -0.739695  0.471111  0.385107  0.194361   77.89
281144 -0.456108 -0.183659 -0.328168  0.606116  0.884876 -0.253700  245.00
281674 -0.072173 -0.450261  0.313267 -0.289617  0.002988 -0.015309   42.53

[915 rows x 30 columns]

In [110]:
X_train ,X_test , Y_train, Y_test = train_test_split(X,Y,test_size=0.2,stratify = Y, random_state=42)

In [111]:
print(X.shape, X_train.shape,X_test.shape)

(915, 30) (732, 30) (183, 30)

In [112]:
model = LogisticRegression(max_iter=10000)

In [113]:
model.fit(X_train,Y_train)

LogisticRegression(max_iter=10000)

In [114]:
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction,Y_train)

In [115]:
print('Acuracy on training data:' ,training_data_accuracy )

Acuracy on training data: 0.953551912568306

In [116]:
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction,Y_test)

In [118]:
print('Acuracy on test data:' ,test_data_accuracy )

Acuracy on test data: 0.9398907103825137